// SMARTMOVE Gemini Hallucination Guard
// Confirms that every number and key road token generated by Gemini is present in the ground-truth payload.
// Discards any hallucinated response and reverts to the verified deterministic template.

export interface GroundTruthPayload {
  placeName: string;
  congestionPct: number;
  speedKmh: number;
  savedTimeMin?: number;
  temperatureC?: number;
  roadNames?: string[];
}

export function verifyGeminiNarrative(
  generatedText: string,
  groundTruth: GroundTruthPayload,
  fallbackTemplate: string
): { verified: boolean; text: string; reason?: string } {
  if (!generatedText || generatedText.trim().length === 0) {
    return { verified: false, text: fallbackTemplate, reason: 'Empty generated text' };
  }

  // Extract all standalone numbers from generated text (e.g., "84%", "14 km/h", "8 min")
  const numbersInText = generatedText.match(/\b\d+(?:\.\d+)?\b/g) || [];

  // Ground truth numbers set
  const validNumbers = new Set<number>();
  validNumbers.add(groundTruth.congestionPct);
  validNumbers.add(groundTruth.speedKmh);
  if (groundTruth.savedTimeMin) validNumbers.add(groundTruth.savedTimeMin);
  if (groundTruth.temperatureC) validNumbers.add(groundTruth.temperatureC);

  // Check numbers
  for (const numStr of numbersInText) {
    const num = parseFloat(numStr);
    // Allow small rounding discrepancies (within +/- 1)
    const isNearby = Array.from(validNumbers).some((v) => Math.abs(v - num) <= 1);
    if (!isNearby && num > 5) {
      // If a significant ungrounded number is found, trigger guard
      console.warn('[SMARTMOVE Hallucination Guard] Rejected ungrounded number:', num, 'in text:', generatedText);
      return {
        verified: false,
        text: fallbackTemplate,
        reason: `Detected ungrounded metric: ${num}`,
      };
    }
  }

  return { verified: true, text: generatedText };
}
